sudo: required

addons:
  apt:
    packages:
      - docker-ce

services:
  - docker

before_script:
  - docker build -t cryptocard .

script:
  - docker run --user 0 cryptocard gradle check --info

notifications:
  email: false